@SoftwareCenter.Api_HostAddress = http://localhost:1337

POST {{SoftwareCenter.Api_HostAddress}}/vendors
Accept: application/json
Content-type: application/json

{

"url": "https://docker.com",
"pointOfContact": {
    "name": "Silvio",
    "email": "silvio@jbrain.com",
    "phone": "800 Write-Code"
}
}


### 

GET {{SoftwareCenter.Api_HostAddress}}/vendors/e506c810-taco-salad


### 
GET {{SoftwareCenter.Api_HostAddress}}/vendors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiI0ZjA1YzgxOCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsIm5iZiI6MTc1Mzk3MzgxNiwiZXhwIjoxNzYxOTIyNjE2LCJpYXQiOjE3NTM5NzM4MTYsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.xzYgp_Tu0cVGcpufNy12MmRyDoINeHF2Oth4h1axv0M